export_path: './exports'
model_path: './saved_models/best_model.pth'
quantization_dataset:
  module_name: src.data.sets.super_resolution
  class_name: FastMRISuperResolutionDataReader
  parameters:
    data_folder: ./val_data_dir
    num_samples: 100
model:
  class_name: SRResUNet
  module_name: src.models.super_resolution
  parameters:
