name: CSnn_100epoch #512hneurons
seed: 1234
track: &track True   # W and B
model:
  class_name: CSNN_bis_reg #ViT_RSNN_NoConv #RSNN_ViT_2
  module_name: src.models.csnn_light
  parameters:
    image_size: 128 #64 # #224 #128
    n_input: 4096
    #patch_size: 16 #32
    #embed_dim: 64
    #n_hidden:  1000 #512 #1000 #1000
    n_output: 11
    n_steps: 5
    #beta: .95
    #threshold: .5


dataloader:
  class_name: BreastMNISTDataloader
  module_name: src.data.loaders.BreastMNIST
  parameters:
    data_dir: ./data
    image_size: 64 #128
    batch_size: 64
    num_workers: 8
    debug: False

trainer:
  class_name: rsnnTrainer
  module_name: src.tasks.rsnn.trainer
  parameters:
    num_epochs: 100
    early_stopping_patience: 20
    lr_scheduler: #plateau #exponential
    lr: 0.0001 #1e-4
    step_size_optim : #10
    weight_decay: 0 #.00001 #0.00001
    gamma_scheduler: 0.5 #0.97

    track: *track
    loss:
      class_name: MSELoss
      module_name: torch.nn
      parameters:
experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment

