name: rsnn_vit_learnablethreshold
seed: 1234
track: &track False   # W and B
model:
  class_name: RSNN_ViT_2
  module_name: src.models.rsnn
  parameters:
    img_size: 128
    patch_size: 16 #32
    embed_dim: 64
    n_hidden:  512 #1000 #1000
    n_output: 1
    n_steps: 5
    beta: .95
    threshold: .5


dataloader:
  class_name: BreastMNISTDataloader
  module_name: src.data.loaders.BreastMNIST
  parameters:
    data_dir: ./data
    image_size: 128
    batch_size: 64
    num_workers: 8
    debug: False

trainer:
  class_name: rsnnTrainer
  module_name: tasks.rsnn.trainer
  parameters:
    num_epochs: 300
    early_stopping_patience: 20
    lr_scheduler: plateau #exponential
    lr: 0.0001
    step_size_optim : 10
    weight_decay: 0 #.00001 #0.00001
    gamma_scheduler: 0.5 #0.97

    track: *track
    loss:
      class_name: MSELoss
      module_name: torch.nn
      parameters:
experiment:
  class_name: BaseExperiment
  module_name: src.core.experiment
